services:
  gateway:
    image: nginx:alpine
    container_name: campus-gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - user-service
      - item-service
      - search-service
      - reservation-service
      - delivery-service
      - notification-service
      - reputation-service
      - traceability-service
      - chat-service

  auth-service:
    build:
      context: ./services/auth-service
    container_name: campus-auth-service

  user-service:
    build:
      context: ./services/user-service
    container_name: campus-user-service

  item-service:
    build:
      context: ./services/item-service
    container_name: campus-item-service
    environment:
      - SERVICE_ROOT_PATH=/items
    expose:
      - "8000"

  search-service:
    build:
      context: ./services/search-service
    container_name: campus-search-service
    environment:
      - SERVICE_ROOT_PATH=/search
    expose:
      - "8000"

  reservation-service:
    build:
      context: ./services/reservation-service
    container_name: campus-reservation-service
    environment:
      - SERVICE_ROOT_PATH=/reservations
    expose:
      - "8000"

  delivery-service:
    build:
      context: ./services/delivery-service
    container_name: campus-delivery-service
    environment:
      - SERVICE_ROOT_PATH=/delivery
    expose:
      - "8000"

  notification-service:
    build:
      context: ./services/notification-service
    container_name: campus-notification-service
    environment:
      - SERVICE_ROOT_PATH=/notifications
    expose:
      - "8000"

  reputation-service:
    build:
      context: ./services/reputation-service
    container_name: campus-reputation-service
    environment:
      - SERVICE_ROOT_PATH=/reputation
    expose:
      - "8000"

  traceability-service:
    build:
      context: ./services/traceability-service
    container_name: campus-traceability-service
    environment:
      - SERVICE_ROOT_PATH=/traceability
    expose:
      - "8000"

  chat-service:
    build:
      context: ./services/chat-service
    container_name: campus-chat-service
    environment:
      - SERVICE_ROOT_PATH=/chat
    expose:
      - "8000"
